apiVersion: v1
kind: Service
metadata:
  name: java-app-service
  labels:
    app: java-app
spec:
  type: NodePort
  selector:
    name: java-app-pod
    app: java-app
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30009