apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: java-app
spec:
  type: NodePort
  selector:
    app: java-app
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30009
